### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by amenk** [vladflonta/magento2-webapi-log#4]
First of all, thanks for this module!

@matheusgontijo will be provide a pull request to add curl-command logging (for replaying requests). Are you interested in merging this or would you like us to publish our fork on packagist.

**Comment by vladflonta** [comment]
Hi @amenk,

Thank you for your interest and your support with this module.
During the past months I've worked on some fixes and improvements (some of which you have already mentioned - I will come back with details when I have them committed) but currently I don't have the possibility to finish those.
Rest assured, there will be new versions coming soon and one of the change includes the possibility to add and configure additional log handlers which will allow to easily process and push the log data to other formats or services. Therefore, I think @matheusgontijo's work would be better suited for a separate package which one might use along with this one.

**Comment by amenk** [comment]
@vladflonta any news :D ? Are you still working on this package?

**Comment by amenk** [comment]
There was a recent release, thanks :-)
