### ISSUE TITLE
Magento 2.4 support?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [vladflonta/magento2-webapi-log#5]
Does not appear to log anything when enabled on Magento 2.4, any thoughts?
Did the interface name change?

**Comment by amenk** [comment]
@LiamKarlMitchell what does not work exactly? Just no longer logging?

**Comment by Tomasz-Silpion** [comment]
For sure in **2.4.5** there's a `Fatal error:  Declaration of VladFlonta\WebApiLog\Logger\Handler\Debug::write(array $record) must be compatible with Magento\Framework\Logger\Handler\Base::write(array $record): void in app/code/VladFlonta/WebApiLog/Logger/Handler/Debug.php on line 23`

No idea how to handle it properly though (maybe with plugin?) so I've changed it manually in filesystem:

```diff --git a/Logger/Handler/Debug.php b/Logger/Handler/Debug.php
index 1d8270c..d8d5449 100644
--- a/Logger/Handler/Debug.php
+++ b/Logger/Handler/Debug.php
@@ -20,7 +20,7 @@ class Debug extends \Magento\Framework\Logger\Handler\Debug
      * @param array $record
      * @throws \Magento\Framework\Exception\LocalizedException
      */
-    public function write(array $record)
+    public function write(array $record): void
     {
         if (!isset($record['context']['is_api']) || !$record['context']['is_api']) {
             parent::write($record);
`
``

**Comment by vladflonta** [comment]
Closing this as it should have been fixed.
